# Identity Setting
# ================
# you should change this to suit your own preference.

title:       Hard Drive Archive
title_short: HDA
description: HDA. Technical and information security blog.
description_short: You do have backups, do you?
logo:        "/images/logo.svg"
cover:       "/images/cover.png"

baseurl: ""                       
url:     ""
owner: https://blog.hda.me/about/about-me

excerpt_separator: <!--more-->

compress_html:
#  blanklines: true
  clippings: [div, p, ul, td, h1, h2, h3, h4]
  endings: [td]
  comments: all
  startings: [head]

# Layout Setting
# ==============
# you may change this to suit your own preference.

timezone:  America/New_York

older_left: false
paginate:   3
mathjax:    false


# Engine Setting
# ==============
# you shouldn't change this unless you really know what you're doing.

paginate_path: "/posts/page:num/"

collections:
  projects:
    output: true
  tools:
    output: false
  about:
    output: true
  services:
    output: false
  news:
    output: false

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      article: true
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: projects
    values:
      layout: project
  - scope:
      path: ""
      type: tools
    values:
      layout: tools
  - scope:
      path: ""
      type: about
    values:
      layout: about
  - scope:
      path: ""
      type: services
    values:
      layout: services
  - scope:
      path: ""
      type: news
    values:
      layout: news
      
sass:
  sass_dir: "_sass/"
  style: compressed

exclude:
  - README.md
  - LICENSE.txt

gems:
  - jekyll-sitemap
  - jekyll-paginate
